apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dotnetdocker-app-hpa
  namespace: sk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnetdocker-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50