apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdocker-app-deployment
  namespace: sk
  labels:
    app: dotnetdocker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdocker-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: dotnetdocker-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - prod
      containers:
        - name: dotnetdocker-app
          image: kiransk.azurecr.io/dotnetdocker-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dotnetdocker-app-deployment
                  key: DB_HOST
       tolerations:
      - key: special
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"            